version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    networks:
      - monitor-network
    depends_on:
      - prometheus
      - redis
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - monitor-network
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    networks:
      - monitor-network
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}

networks:
  monitor-network:
    driver: bridge

volumes:
  redis-data:
  grafana-storage: