{
 "title": "Factory",
 "time": { "from": "2025-05-20T02:13:16.428Z", "to": "2025-05-21T02:13:16.428Z" },
 "panels": [
  { "title": "Taipei", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Command_Center",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "earthquake_alerts_command_center{location=\"Taipei\"}",
     "legendFormat": "{{origin_time}}"
    }
   ]
  },
  {
   "title": "Intensity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "earthquake_intensity{area=\"Taipei\"}",
     "legendFormat": "Intensity"
    }
   ]
  },
  {
   "title": "Damages",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "earthquake_alerts_damage{location=\"Taipei\"}",
     "legendFormat": "{{origin_time}}"
    }
   ]
  },
  { "title": "Hsinchu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Command_Center",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "earthquake_alerts_command_center{location=\"Hsinchu\"}",
     "legendFormat": "{{origin_time}}"
    }
   ]
  },
  {
   "title": "Intensity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "earthquake_intensity{area=\"Hsinchu\"}",
     "legendFormat": "Intensity"
    }
   ]
  },
  {
   "title": "Damages",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "earthquake_alerts_damage{location=\"Hsinchu\"}",
     "legendFormat": "{{origin_time}}"
    }
   ]
  },
  { "title": "Taichung", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Command_Center",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "earthquake_alerts_command_center{location=\"Taichung\"}",
     "legendFormat": "{{origin_time}}"
    }
   ]
  },
  {
   "title": "Intensity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "earthquake_intensity{area=\"Taichung\"}",
     "legendFormat": "Intensity"
    }
   ]
  },
  {
   "title": "Damages",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "earthquake_alerts_damage{location=\"Taichung\"}",
     "legendFormat": "{{origin_time}}"
    }
   ]
  },
  { "title": "Tainan", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Command_Center",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "earthquake_alerts_command_center{location=\"Tainan\"}",
     "legendFormat": "{{origin_time}}"
    }
   ]
  },
  {
   "title": "Intensity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "earthquake_intensity{area=\"Tainan\"}",
     "legendFormat": "Intensity"
    }
   ]
  },
  {
   "title": "Damages",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "earthquake_alerts_damage{location=\"Tainan\"}",
     "legendFormat": "{{origin_time}}"
    }
   ]
  }
 ]
}