{
 "title": "Report",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Average Processing Duration",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(earthquake_alerts_processing_duration)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(earthquake_alerts_total)", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Processed Alerts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(earthquake_alerts_processed_total)",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}