{
 "title": "Earthquake Monitoring Dashboard",
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Earthquake Occurrences",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 9 },
   "targets": [
    { "expr": "earthquake_occurrences_total{}" }
   ]
  },
  {
   "title": "Earthquake Magnitude",
   "type": "graph",
   "gridPos": { "x": 0, "y": 9, "w": 24, "h": 9 },
   "targets": [
    { "expr": "earthquake_magnitude{}" }
   ]
  },
  {
   "title": "Earthquake Depth",
   "type": "graph",
   "gridPos": { "x": 0, "y": 18, "w": 24, "h": 9 },
   "targets": [
    { "expr": "earthquake_depth{}" }
   ]
  },
  {
   "title": "Earthquake Intensity",
   "type": "graph",
   "gridPos": { "x": 0, "y": 27, "w": 24, "h": 9 },
   "targets": [
    { "expr": "earthquake_intensity{}" }
   ]
  },
  {
   "title": "Earthquake Event Count",
   "type": "graph",
   "gridPos": { "x": 0, "y": 36, "w": 24, "h": 9 },
   "targets": [
    { "expr": "earthquake_events_total" }
   ]
  },
  {
   "title": "Earthquake Event Severity",
   "type": "graph",
   "gridPos": { "x": 0, "y": 45, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "earthquake_event_severity_level"
    }
   ]
  },
  {
   "title": "Earthquake Alert Count",
   "type": "graph",
   "gridPos": { "x": 0, "y": 54, "w": 24, "h": 9 },
   "targets": [
    { "expr": "earthquake_alerts_total" }
   ]
  },
  {
   "title": "Earthquake Alerts with Damage",
   "type": "graph",
   "gridPos": { "x": 0, "y": 63, "w": 24, "h": 9 },
   "targets": [
    { "expr": "earthquake_alerts_damage" }
   ]
  },
  {
   "title": "Earthquake Alerts with Command Center Need",
   "type": "graph",
   "gridPos": { "x": 0, "y": 72, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "earthquake_alerts_command_center"
    }
   ]
  }
 ]
}